package com.sameershelar.bloodalcoholcalculator.utils

object Constants {

    enum class DrinkType {
        BEER,
        WHISKY,
        VODKA,
        RUM,
        WINE,
        GIN,
        BRANDY,
    }

    val legalLimits: HashMap<String, Float> = hashMapOf(
        "Angola" to 0.06f,
        "Algeria" to 0.02f,
        "Benin" to 0.05f,
        "Cape Verde" to 0.08f,
        "Central African Republic" to 0.08f,
        "Comoros" to 0.0f,
        "Congo" to 0.05f,
        "Egypt" to 0.05f,
        "Equatorial Guinea" to 0.05f,
        "Eritrea for commercial" to 0.03f,
        "Eritrea" to 0.05f,
        "Ethiopia" to 0.08f,
        "The Gambia" to 0f,
        "Ghana" to 0.08f,
        "Guinea" to 0.08f,
        "Guinea-Bissau" to 0f,
        "Kenya" to 0.08f,
        "Libya" to 0.0f,
        "Malawi" to 0.08f,
        "Mauritius" to 0.05f,
        "Morocco" to 0.02f,
        "Namibia" to 0.05f,
        "Niger" to 0f,
        "Nigeria" to 0.05f,
        "Rwanda" to 0.08f,
        "Seychelles" to 0.08f,
        "South Africa" to 0.05f,
        "South Africa for professional" to 0.02f,
        "Togo" to 0f,
        "Uganda" to 0.08f,
        "Tanzania for commercial" to 0.0f,
        "Tanzania" to 0.08f,
        "Zambia" to 0.08f,
        "Canada" to 0.08f,
        "Canada for new drivers" to 0.00f,
        "Mexico" to 0.10f,
        "United States" to 0.08f,
        "United States for commercial" to 0.04f,
        "Bahamas" to 0.08f,
        "Cuba" to 0.05f,
        "Cuba for new/professional" to 0.00f,
        "Dominican Republic" to 0.05f,
        "Jamaica" to 0.08f,
        "Trinidad and Tobago" to 0.08f,
        "Cayman Islands" to 0.10f,
        "Belize" to 0.08f,
        "Costa Rica" to 0.05f,
        "Costa Rica for commercial/new" to 0.02f,
        "El Salvador" to 0.05f,
        "Guatemala" to 0.08f,
        "Honduras" to 0.07f,
        "Nicaragua" to 0.05f,
        "Panama" to 0.08f,
        "Argentina" to 0.00f,
        "Bolivia" to 0.05f,
        "Brazil" to 0.00f,
        "Chile" to 0.08f,
        "Chile for under influence" to 0.03f,
        "Colombia" to 0.15f,
        "Ecuador" to 0.03f,
        "Ecuador for commercial" to 0.01f,
        "Guyana" to 0.08f,
        "Paraguay" to 0.00f,
        "Peru" to 0.05f,
        "Suriname" to 0.05f,
        "Uruguay" to 0.00f,
        "Venezuela" to 0.08f,
        "Mongolia" to 0.05f,
        "Turkmenistan" to 0.03f,
        "Mainland China" to 0.02f,
        "Hong Kong" to 0.05f,
        "Japan" to 0.03f,
        "South Korea" to 0.08f,
        "Taiwan" to 0.03f,
        "Afghanistan" to 0.00f,
        "Bangladesh" to 0.00f,
        "India" to 0.03f,
        "Nepal" to 0.00f,
        "Pakistan" to 0.00f,
        "Sri Lanka" to 0.06f,
        "Brunei" to 0.08f,
        "Cambodia" to 0.05f,
        "Indonesia" to 0.00f,
        "Laos" to 0.08f,
        "Malaysia" to 0.08f,
        "Malaysia" to 0.022f,
        "Philippines" to 0.05f,
        "Philippines for motorcycle/professional" to 0.01f,
        "Singapore" to 0.08f,
        "Thailand" to 0.05f,
        "Thailand for commercial" to 0.00f,
        "Vietnam" to 0.00f,
        "Armenia" to 0.02f,
        "Azerbaijan" to 0.00f,
        "Bahrain" to 0.00f,
        "Iraq" to 0.04f,
        "Israel" to 0.024f,
        "Israel for new/commercial" to 0.005f,
        "Jordan" to 0.05f,
        "Lebanon" to 0.02f,
        "Oman" to 0.08f,
        "Qatar" to 0.00f,
        "Turkey" to 0.05f,
        "Turkey for commercial" to 0.00f,
        "Turkey for beginners" to 0.03f,
        "United Arab Emirates" to 0.00f,
        "Albania" to 0.01f,
        "Andorra" to 0.05f,
        "Austria" to 0.05f,
        "Austria for new/commercial" to 0.01f,
        "Belarus" to 0.03f,
        "Belgium" to 0.05f,
        "Bosnia and Herzegovina" to 0.03f,
        "Bulgaria" to 0.05f,
        "Croatia" to 0.05f,
        "Croatia for new/professional" to 0.00f,
        "Cyprus" to 0.05f,
        "Cyprus - gram per liter" to 0.22f,
        "Northern Cyprus" to 0.05f,
        "Czech Republic" to 0.00f,
        "Denmark" to 0.05f,
        "Estonia" to 0.02f,
        "Finland" to 0.05f,
        "France" to 0.05f,
        "France for new/commercial" to 0.02f,
        "Georgia" to 0.03f,
        "Germany" to 0.00f,
        "Germany - cyclists" to 0.16f,
        "Gibraltar" to 0.05f,
        "Greece" to 0.05f,
        "Hungary" to 0.00f,
        "Iceland" to 0.02f,
        "Republic of Ireland" to 0.05f,
        "Italy" to 0.05f,
        "Latvia" to 0.02f,
        "Liechtenstein" to 0.08f,
        "Lithuania" to 0.00f,
        "Luxembourg" to 0.02f,
        "Malta" to 0.08f,
        "Moldova" to 0.03f,
        "Montenegro" to 0.03f,
        "Netherlands" to 0.05f,
        "Netherlands for new" to 0.02f,
        "North Macedonia" to 0.00f,
        "Norway" to 0.02f,
        "Poland" to 0.02f,
        "Portugal" to 0.05f,
        "Romania" to 0.00f,
        "Russian Federation" to 0.0356f,
        "Serbia" to 0.02f,
        "Slovakia" to 0.00f,
        "Slovenia" to 0.00f,
        "Spain" to 0.05f,
        "Sweden" to 0.02f,
        "Switzerland" to 0.00f,
        "Ukraine" to 0.02f,
        "United Kingdom - England" to 0.08f,
        "United Kingdom - Wales" to 0.08f,
        "United Kingdom - Northern Ireland" to 0.08f,
        "United Kingdom - Scotland" to 0.05f,
        "Australian Capital Territory" to 0.05f,
        "New South Wales" to 0.05f,
        "Northern Territory" to 0.05f,
        "Queensland" to 0.05f,
        "South Australia" to 0.05f,
        "Tasmania" to 0.05f,
        "Victoria" to 0.05f,
        "Western Australia" to 0.05f,
        "New Zealand" to 0.05f,
        "French Polynesia" to 0.05f,
        "Micronesia" to 0.05f,
        "Fiji - General Population" to 0.08f,
        "Fiji for new/professional" to 0.0f,
        "Palau for new/professional" to 0.0f,
        "Palau" to 0.10f
    )
}